/* itoa.cc  rev 8/98*/

/* This function converts integers between 0 and 99 to two digits- ascii form.
   e.g., 5 becomes 05.
   These numbers are used to make directories in the shell script file batch*.
   All directories generated by the shell script will have the same length
   for directory names.
   Later in matlab, when we use petmanip* to descend directories,
   all direcotry names must have the same length.  This will 
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


void itoa(int p, char sp[])
{
  int i;
  i = p/10;

  if(i == 0)
    {
      sp[0] = '0';
      sp[1] = '0' + p;
    }
  else
    {
      sp[0] = '0' + i;
      sp[1] = '0' + (p - i*10);
    }
  sp[2] = '\0';
}
